.\" 
.\" XMMS2 Collection parser.
.\"
.\" xmcollparse.3 - Collection parser high level API.
.\"
.\" Copyright (C) 2010 Raphaël Bois
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.TH XMCOLLPARSE 3 "Draft 0.1" "" "Draft 0.1"
.SH NAME
.PP
xm_coll_compile_pattern, xm_coll_check_pattern \- generate a collection from a
query string
.SH SYNOPSIS
.PP
.B #include <coll-parser.h>
.PP
.PP
.BI "xmmsv_t *xm_coll_compile_pattern(const char *" pattern );
.PP
.BI "xmmsv_t *xm_coll_compile_pattern(const char *" pattern ", xmmsv_t **" error );
.SH DESCRIPTION
.PP
The \fBxm_coll_compile_pattern\fP() function returns the collection generated
from \fIpattern\fP.
.PP
The \fBxm_coll_check_pattern\fP() function check if \fIpattern\fP contains
errors without generating the collection. \fIerror\fP can be either a return
location for an error value or NULL.
.SH "RETURN VALUE"
.PP
The \fBxm_coll_compile_pattern\fP() function returns a pointer to an xmmsv
structure that contains the generated collection or an error if \fIpattern\fP
is not valid
.RB "(See " xmpattern (7)).
.PP
The \fBxm_coll_check_pattern\fP() function returns 1 if \fIpattern\fP is valid.
If an error occurs, it returns 0 and an error value is returned at the location
pointed by \fIerror\fP if any is provided.
.SH "SEE ALSO"
.BR xmpattern (7)
.SH BUGS
The XMMS2 Collection Parser library is still in development and may retain a
lot of unknown bugs. You can check for bugs and/or report new ones at
http://github.com/vdust/xmms2-coll-parser/issues
.SH AUTHOR
This manual page was written by Raphael Bois <virtualdust@gmail.com>
